import { useTranslations } from "next-intl";
import SwiperComponent from "../Swiper/Swiper";
import s from "./Gallery.module.css";
import SocialLinks from "../SocialLinks/SocialLinks";


const GalleryImg = [
  // "/images/gallery/gallery-001.jpg",
  // "/images/gallery/gallery-002.jpg",
  // "/images/gallery/gallery-003.jpg",
  // "/images/gallery/gallery-004.jpg",
  "/images/gallery/gallery-005.jpg",
  "/images/gallery/gallery-006.jpg",
  "/images/gallery/gallery-007.jpg",
  "/images/gallery/gallery-008.jpg",
  "/images/gallery/gallery-009.jpg",
  "/images/gallery/gallery-010.jpg",
  "/images/gallery/gallery-011.jpg",
  "/images/gallery/gallery-012.jpg",
  "/images/gallery/gallery-013.jpg",
  "/images/gallery/gallery-014.jpg",
  "/images/gallery/gallery-015.jpg",
  "/images/gallery/gallery-016.jpg",
  "/images/gallery/gallery-017.jpg",
  "/images/gallery/gallery-018.jpg",
  "/images/gallery/gallery-019.jpg",
  "/images/gallery/gallery-020.jpg",
  "/images/gallery/gallery-021.jpg",
  "/images/gallery/gallery-022.jpg",
  "/images/gallery/gallery-023.jpg",
  "/images/gallery/gallery-024.jpg",
  "/images/gallery/gallery-025.jpg",
  "/images/gallery/gallery-026.jpg",
  "/images/gallery/gallery-027.jpg",
  // "/images/gallery/gallery-028.jpg",
  // "/images/gallery/gallery-029.jpg",
  "/images/gallery/gallery-030.jpg",
  "/images/gallery/gallery-031.jpg",
  "/images/gallery/gallery-032.jpg",
  // "/images/gallery/gallery-033.jpg",
  "/images/gallery/gallery-034.jpg",
  "/images/gallery/gallery-035.jpg",
  "/images/gallery/gallery-036.jpg",
  "/images/gallery/gallery-037.jpg",
  // "/images/gallery/gallery-038.jpg",
  "/images/gallery/gallery-039.jpg",
  "/images/gallery/gallery-040.jpg",
  "/images/gallery/gallery-041.jpg",
  "/images/gallery/gallery-042.jpg",
  "/images/gallery/gallery-043.jpg",
  // "/images/gallery/gallery-044.jpg",
  "/images/gallery/gallery-045.jpg",
  // "/images/gallery/gallery-046.jpg",
  "/images/gallery/gallery-047.jpg",
  "/images/gallery/gallery-048.jpg",
  "/images/gallery/gallery-049.jpg",
  "/images/gallery/gallery-050.jpg",
  "/images/gallery/gallery-051.jpg",
  "/images/gallery/gallery-052.jpg",
  "/images/gallery/gallery-053.jpg",
  "/images/gallery/gallery-054.jpg",
  "/images/gallery/gallery-055.jpg",
  "/images/gallery/gallery-056.jpg",
  "/images/gallery/gallery-057.jpg",
  "/images/gallery/gallery-058.jpg",
  "/images/gallery/gallery-059.jpg",
  "/images/gallery/gallery-060.jpg",
  "/images/gallery/gallery-061.jpg",
  "/images/gallery/gallery-062.jpg",
  "/images/gallery/gallery-063.jpg",
  "/images/gallery/gallery-064.jpg",
  "/images/gallery/gallery-065.jpg",
  "/images/gallery/gallery-066.jpg",
  "/images/gallery/gallery-067.jpg",
  "/images/gallery/gallery-068.jpg",
  "/images/gallery/gallery-069.jpg",
  "/images/gallery/gallery-070.jpg",
  "/images/gallery/gallery-071.jpg",
  "/images/gallery/gallery-072.jpg",
  "/images/gallery/gallery-073.jpg",
  "/images/gallery/gallery-074.jpg",
  "/images/gallery/gallery-075.jpg",
  "/images/gallery/gallery-076.jpg",
  // "/images/gallery/gallery-077.jpg",
  // "/images/gallery/gallery-078.jpg",
  // "/images/gallery/gallery-079.jpg",
  "/images/gallery/gallery-080.jpg",
  "/images/gallery/gallery-081.jpg",
  "/images/gallery/gallery-082.jpg",
  "/images/gallery/gallery-083.jpg",
  "/images/gallery/gallery-084.jpg",
  "/images/gallery/gallery-085.jpg",
  // "/images/gallery/gallery-086.jpg",
  "/images/gallery/gallery-087.jpg",
  // "/images/gallery/gallery-088.jpg",
  "/images/gallery/gallery-089.jpg",
  // "/images/gallery/gallery-090.jpg",
  // "/images/gallery/gallery-091.jpg",
  // "/images/gallery/gallery-092.jpg",
  // "/images/gallery/gallery-093.jpg",
  // "/images/gallery/gallery-094.jpg",
  // "/images/gallery/gallery-095.jpg",
  // "/images/gallery/gallery-096.jpg",
  // "/images/gallery/gallery-097.jpg",
  "/images/gallery/gallery-098.jpg",
  "/images/gallery/gallery-099.jpg",
  "/images/gallery/gallery-100.jpg",
  "/images/gallery/gallery-101.jpg",
  "/images/gallery/gallery-102.jpg",
  "/images/gallery/gallery-103.jpg",
  "/images/gallery/gallery-104.jpg",
  "/images/gallery/gallery-105.jpg",
  "/images/gallery/gallery-106.jpg",
  "/images/gallery/gallery-107.jpg",
  // "/images/gallery/gallery-108.jpg",
  // "/images/gallery/gallery-109.jpg",
  "/images/gallery/gallery-110.jpg",
  "/images/gallery/gallery-111.jpg",
  "/images/gallery/gallery-112.jpg",
  // "/images/gallery/gallery-113.jpg",
  // "/images/gallery/gallery-114.jpg",
  // "/images/gallery/gallery-115.jpg",
  // "/images/gallery/gallery-116.jpg",
  // "/images/gallery/gallery-117.jpg",
  "/images/gallery/gallery-118.jpg",
  "/images/gallery/gallery-119.jpg",
  "/images/gallery/gallery-120.jpg",
  "/images/gallery/gallery-121.jpg",
  "/images/gallery/gallery-122.jpg",
  "/images/gallery/gallery-123.jpg",
  "/images/gallery/gallery-124.jpg",
  "/images/gallery/gallery-125.jpg",
  "/images/gallery/gallery-126.jpg",
  "/images/gallery/gallery-127.jpg",
  "/images/gallery/gallery-128.jpg",
  "/images/gallery/gallery-129.jpg",
  "/images/gallery/gallery-130.jpg",
  "/images/gallery/gallery-131.jpg",
  "/images/gallery/gallery-132.jpg",
  "/images/gallery/gallery-133.jpg",
  "/images/gallery/gallery-134.jpg",
  // "/images/gallery/gallery-135.jpg",
  "/images/gallery/gallery-136.jpg",
  "/images/gallery/gallery-137.jpg",
  "/images/gallery/gallery-138.jpg",
];

const Gallery = () => {
    const t = useTranslations('Gallery');
  return (
    <div className={s.section}>
      <div className={s.body}>
      <div className={s.descr}>
          <p className={s.descrText}>{t("desc1")}</p>
        </div>
      <SocialLinks/>
              {/* <h3 className={s.title}>{t("title")}</h3> */}
        <SwiperComponent images={GalleryImg} />
        
       
      </div>
    </div>
  );
}; 

export default Gallery;
