// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import './globals.css';
// import Header from '@/components/Header';
// import Footer from '@/components/footer';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// interface RootLayoutProps {
//   children: React.ReactNode;
//   params: {
//     locale: string;
//   };
// }
// export default function RootLayout({
//   children,
//   params: { locale },
// }: Readonly<RootLayoutProps>) {
//   return (
//     <html lang={locale}>
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/css2?family=Rounded+Mplus+1c:wght@300;400;500;700&family=Inter:wght@300;400;500;700&family=Open+Sans:wght@300;400;600&display=swap"
//         />
//       </head>
//       <body className={inter.className}>
//         <div className='flex flex-col min-h-screen max-w-4xl mx-auto'>
//           <Header />
//           <div className='flex-grow mt-20'>{children}</div>
//           <Footer />
//         </div>
//       </body>
//     </html>
//   );
// }
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/footer";
// import { NextIntlClientProvider } from "next-intl";
// import { notFound } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// interface RootLayoutProps {
//   children: React.ReactNode;
//   params: {
//     locale: string;
//   };
// }


// export default function RootLayout({
//   children,
//   params: { locale },
// }: Readonly<RootLayoutProps>) {
//   // Список підтримуваних мов
//   const availableLocales = ["en", "uk"];

//   if (!availableLocales.includes(locale)) {
//     notFound();
//   }

//   return (
//     <html lang={locale}>
//       <head>
//         <link
//           rel="stylesheet"
//           href="https://fonts.googleapis.com/css2?family=Rounded+Mplus+1c:wght@300;400;500;700&family=Inter:wght@300;400;500;700&family=Open+Sans:wght@300;400;600&display=swap"
//         />
//       </head>
//       <body className={inter.className}>
//         <NextIntlClientProvider locale={locale} >
//           <div className="flex flex-col min-h-screen max-w-4xl mx-auto">
//             <Header />
//             <div className="flex-grow mt-20">{children}</div>
//             <Footer />
//           </div>
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { unstable_setRequestLocale } from 'next-intl/server';
import Header from "../../components/Header";

import "./globals.css";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function RootLayout({
  children,
  params: { locale },
  
}: RootLayoutProps) {
    unstable_setRequestLocale(locale); // ← ДОДАЙ СЮДИ
  const availableLocales = ["en", "uk", "pl"];
  if (!availableLocales.includes(locale)) {
    notFound();
  }

  // ОТРИМУЄМО ПЕРЕКЛАДИ
  const messages = (await import(`../../../messages/${locale}.json`)).default;

  return (
    <html lang={locale}>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Rounded+Mplus+1c:wght@300;400;500;700&family=Inter:wght@300;400;500;700&family=Open+Sans:wght@300;400;600&display=swap"
        />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <div className="flex flex-col min-h-screen max-w-4xl mx-auto">
            <Header />
            <div className="flex-grow mt-20">{children}</div>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
